{
 "title": "HKV",
 "time": { "from": "2025-01-20T18:38:49.538Z", "to": "2025-01-20T18:38:55.002Z" },
 "panels": [
  {
   "title": "HKV Verteiler - XX",
   "type": "timeseries",
   "description": "HKV Verteiler - XX",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BucketMeaserments\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"temperature\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.alias == \"esp32-XXXXXX\")\n  |> group(columns: [\"sensor\",\"room\"])\n  |> sort(columns: [\"_time\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "HKV Verteiler - YY",
   "type": "timeseries",
   "description": "HKV Verteiler - YY",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BucketMeaserments\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"temperature\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.alias == \"esp32-YYYYYY\")\n  |> group(columns: [\"sensor\",\"room\"])\n  |> sort(columns: [\"_time\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "HKV Verteiler - ZZ",
   "type": "timeseries",
   "description": "HKV Verteiler - ZZ",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BucketMeaserments\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"temperature\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.alias == \"esp32-ZZZZZZ\")\n  |> group(columns: [\"sensor\",\"room\"])\n  |> sort(columns: [\"_time\"])\n  |> yield()\n"
    }
   ]
  }
 ]
}